### ISSUE TITLE
Sub-Pages

### ISSUE THREAD

**Issue by sbrl** [sbrl/Pepperminty-Wiki#6]
We should implement sub pages.

Things that need checking / doing:

 - [x] Check that the page name escaper correctly handles forward slashes
 - [x] Add support for sub-pages to the page index
    - [x] Add field that indicates whether a given pages has any sub pages
 - [x] Update the `page-list` extension to support sub-pages
 - [x] Add support for sub pages to the page index rebuilder
 - [x] Allow sub pages to be saved in sub folders
 - [x] Display a configurable list of sub pages on pages that have sub pages

Update:

Bugs to fix before this is done:

 - [x] Fix issue #11 - Non-existent subpage parents aren't added to $pageindex->$page->subpages
 - [x] Fix issue #12 - Creating a page with a non-existent parent doesn't cause the parent to be created
 - [x] Fix issue #13 - Creating a sub page doesn't result the subpage[] entry being updated

**Comment by sbrl** [comment]
Updating the page name escaper to allow forward slashes is easy - it's adding the field that gives a list of all the sub pages every page has that will be slightly more challenging. Perhaps for the page index rebuilder we could add this field in *after* the index has been built.

**Comment by sbrl** [comment]
The page index rebuilder works with subpages now!
You can also create / save subpages too, but the page index doesn't get updated quite right yet (issue #13).

More tasks before this is done:

 - [ ] Fix issue #11 - Non-existent subpage parents aren't added to $pageindex->$page->subpages
 - [ ] Fix issue #12 - Creating a page with a non-existent parent doesn't cause the parent to be created
 - [ ] Fix issue #13 - Creating a sub page doesn't result the subpage[] entry being updated

**Comment by sbrl** [comment]
Achievement get: Add subpages!
